FROM docker.io/nvidia/cuda:10.0-cudnn7-devel-ubi7
LABEL MAINTAINER="Avishkar Gupta <avgupta@redhat.com>"

RUN dnf install -y git python3 && python3 -m pip install --upgrade pip virtualenv setuptools

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m virtualenv --python=/usr/bin/python3 $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Helps speedup docker build time.
ADD model_inference_triage_pipeline/requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
