apiVersion: v1
kind: Template
labels:
  template: probable-vulnerabilities-inference
metadata:
  name: probable-vulnerabilities-inference
  annotations:
    description: probable-vulnerabilities-inference
objects:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: bert-inference
  spec:
    schedule: "${CRON_SCHEDULE}"
    startingDeadlineSeconds: 200
    successfulJobsHistoryLimit: 5
    failedJobsHistoryLimit: 5
    concurrencyPolicy: "Forbid"
    replicas: "${{REPLICAS}}"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              parent: bert-inference
          spec:
            restartPolicy: OnFailure
            volumes:
            - name: credentials
              secret:
                secretName: google-big-query
                items:
                -  key: bq.json
                   path: gcloud/google-services.json
            - name: model-assets
              emptyDir: {}
            containers:
            - env:
              - name: DAYS
                value: ${DAYS}
              - name: BIGQUERY_CREDENTIALS_FILEPATH
                value: "/etc/credentials/gcloud/google-services.json"
              - name: CVE_MODEL
                value: ${CVE_MODEL}
              - name: OSA_API_SERVER_HOST
                value: ${OSA_API_SERVER_HOST}
              - name: OSA_API_SERVER_PORT
                value: ${OSA_API_SERVER_PORT}
              - name: SKIP_INSERT_API_CALL
                value: ${SKIP_INSERT_API_CALL}
              - name: DATA_INSERT_CONCURRENCY
                value: ${DATA_INSERT_CONCURRENCY}
              - name: S3_MODEL_BUCKET
                valueFrom:
                  secretKeyRef:
                    key: bucket
                    name: openshift-probable-vulnerability-models-s3
              - name: S3_MODEL_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    key: aws_access_key_id
                    name: openshift-probable-vulnerability-models-s3
              - name: S3_MODEL_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    key: aws_secret_access_key
                    name: openshift-probable-vulnerability-models-s3
              - name: S3_INFERENCE_BUCKET
                valueFrom:
                  secretKeyRef:
                    key: bucket
                    name: openshift-probable-vulnerability-inference-result-s3
              - name: S3_INFERENCE_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    key: aws_access_key_id
                    name: openshift-probable-vulnerability-inference-result-s3
              - name: S3_INFERENCE_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    key: aws_secret_access_key
                    name: openshift-probable-vulnerability-inference-result-s3
              - name: SENTRY_DSN
                valueFrom:
                  secretKeyRef:
                    name: osa
                    key: sentry_dsn
              volumeMounts:
                - name: credentials
                  mountPath: "/etc/credentials/"
                  readOnly: true
                - name: model-assets
                  mountPath: "/model_assets"
              image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
              imagePullPolicy: Always
              name: openshift-probable-vulnerabilities
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}

parameters:
- description: CPU request
  displayName: CPU request
  required: true
  name: CPU_REQUEST
  value: "125m"

- description: CPU limit
  displayName: CPU limit
  required: true
  name: CPU_LIMIT
  value: "4"

- description: Memory request
  displayName: Memory request
  required: true
  name: MEMORY_REQUEST
  value: "6Gi"

- description: Memory limit
  displayName: Memory limit
  required: true
  name: MEMORY_LIMIT
  value: "8Gi"

- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "quay.io"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "openshiftio/openshift-probable-vulnerabilities"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"

- description: Number of deployment replicas
  displayName: Number of deployment replicas
  required: true
  name: REPLICAS
  value: "1"

- description: "The number of days for which the inference has to be run."
  displayName: Days for which report needs to be run
  required: true
  name: DAYS
  value: "1"

- description: "The CVE model type to use for inference, accepted values - bert/bert_torch/gru"
  displayName: CVE Model Name
  required: true
  name: CVE_MODEL
  value: "bert_torch"

- description: "OSA API Server Host"
  displayName: OSA API Server Host
  required: true
  name: OSA_API_SERVER_HOST
  value: "osa-api-server"

- description: "OSA API Server Port"
  displayName: OSA API Server Port
  required: true
  name: OSA_API_SERVER_PORT
  value: "5000"

- description: "Flag that heps to skip API call which is doing insertion of inference output to db via api server"
  displayName: Skip Insert API Call
  required: true
  name: SKIP_INSERT_API_CALL
  value: "false"

- description: "No of concurrent request allowed for data insertion"
  displayName: Data Insert Concurrency
  required: true
  name: DATA_INSERT_CONCURRENCY
  value: "3"

- description: "CronJob scheduler value"
  displayName: CronJob scheduler value
  required: true
  name: CRON_SCHEDULE
  # Updating cron to 30th feb so it wont execute anytime. 
  value: "0 1 30 2 *"
